# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Analytics', '~> 5.20.1'
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Auth', '~> 5.20.1'
pod 'Firebase/Firestore', '~> 5.20.1'
pod 'FBSDKCoreKit', '~> 4.39.1'
pod 'FBSDKLoginKit', '~> 4.39.1'
pod 'FBSDKShareKit', '~> 4.39.1'

target 'Shopertino' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RestaurantApp

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  target 'ShopertinoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Shopertino-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RestaurantApp-tvOS

  target 'Shopertino-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
